# Generated by Django 4.2.23 on 2025-11-22 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_skillgapanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('recommendations', models.JSONField()),
                ('raw_prompt', models.TextField(blank=True, null=True)),
                ('raw_response', models.TextField(blank=True, null=True)),
                ('quiz_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.quizsubmission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
