# Generated by Django 4.2.23 on 2025-08-24 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_roadmap', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.quizsubmission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
